dist: focal
os: linux
language: python
jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
cache:
  directories:
    - $HOME/.cache/pip
services:
  - elasticsearch
install:
  - pip install tox coveralls
before_script:
  - sleep 10
script:
  - tox --recreate
after_success:
  - coveralls
